[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = "9.3.1"
chrono = "0.4.41"
domain = { path = "../domain" }
api = { path = "../api" }
serde = "1.0.219"
argon2 = "0.5.3"
password-hash = "0.5.0"
rand = "0.9.2"
